### PR TITLE
Update CI.yml

### PR DESCRIPTION
**Pull request by storopoli**
I need to have workflow dispatch enabled to debug CI GitHub Actions, specially Documentation workflow.

### CODE REVIEW

**Comment by storopoli** [comment]
Well, the thing seems to run OK now! So definitely the previous PR Action was using a cached `DOCUMENTER_KEY` that was not in base 64. The updated `DOCUMENTER_KEY` repo secret is in base 64 (requirement by `Documenter.jl`)

**Comment by rikhuijzer** [comment]
> Well, the thing seems to run OK now! So definitely the previous PR Action was using a cached `DOCUMENTER_KEY` that was not in base 64. The updated `DOCUMENTER_KEY` repo secret is in base 64 (requirement by `Documenter.jl`)

Ah okay. Good to know. I always use `DocumenterTools.genkeys()` so never noticed that

**Comment by storopoli** [comment]
So that's crazy! PR GH Actions pass and then when we merge it fails! #wtf

**Comment by rikhuijzer** [comment]
> So that's crazy! PR GH Actions pass and then when we merge it fails! #wtf

It doesn't use the key on the PR branch so it makes sense right?

**Comment by storopoli** [comment]
Oh right. Yeah you are probably right.

**Pull request merged**
