### PR TITLE
Remove CI badge

### PR DESCRIPTION
**Pull request by rikhuijzer**
Let's remove it? The badge is always red due to nightly anyway

### CODE REVIEW

**Comment by storopoli** [comment]
@yebai has said that the expectation for Turing to work in 1.7 is late this month.
We should keep it. The badge would be important in the future where Turing works in nightly and 1.7.

**Comment by rikhuijzer** [comment]
Nightly fails all the time

**Comment by storopoli** [comment]
Ok, what about if we keep the badge and remove nightly?

**Comment by rikhuijzer** [comment]
Sounds good

**Pull request closed without merging**
